version: '3'

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-kos-fe-development
    ports:
      - '0.0.0.0:3333:3333'